version: '3'

services:
  api:
    image: questrade2023-api
    build: ../loan-application-api/loan-application-api/
    command: --environment Development
    ports:
      - "5287:80"

  web:
    image: questrade2023-web
    build:
      context: ../loan-application-frontend/
      args:
        - VITE_API_BASE_URL=/api
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
      - "8080:80"
